classdef TestNormalize < matlab.unittest.TestCase

properties (TestParameter)
p = init_norm()
end

methods (Test)
function test_normalize(tc, p)
tc.verifyEqual(stdlib.normalize(p{1}), p{2})
end
end

end

function p = init_norm()

p = {
  {"", "."}, ...
  {"a/..", "."}, ...
  {"//a/b/", "/a/b"}, ...
  {"/a/b/", "/a/b"},  ...
  {"a/b/", "a/b"}, ...
  {"a/../c", "c"}, ...
  {"a/b/../c", "a/c"}, ...
  {"a/b/../../c", "c"}, ...
  {"a/b/../../c/..", "."}, ...
  {"a/b/../../c/../..", ".."}, ...
  {"a////b", "a/b"}, ...
  {".a", ".a"}, ...
  {"..a", "..a"}, ...
  {"a.", "a."}, ...
  {"a..", "a.."}, ...
  {"./a/.", "a"}, ...
  {"../a", "../a"}
};

if ispc
  p{3}{2} = "//a/b";
end
end
