classdef (SharedTestFixtures={ matlab.unittest.fixtures.PathFixture(fileparts(fileparts(mfilename('fullpath'))))}, ...
          TestTags = {'R2019a', 'pure'}) ...
    TestJoin < matlab.unittest.TestCase

properties (TestParameter)
p = {{"", "", ""}, ...
{"a", "", "a"}, ...
{"", "a", "a"}, ...
{"a/b/", "c", "a/b/c"}, ...
{"/", "", "/"}, ...
{"", "/", "/"}, ...
{'a', 'b', 'a/b'}, ...
{"a/b/../", "c/d/..", "a/b/../c/d/.."}, ...
{"a/b", "..", "a/b/.."}, ...
{"a/b", "c/d", "a/b/c/d"}, ...
{"ab/cd", "/ef", "/ef"}, ...
{matlabroot, "bin", matlabroot + "/bin"}
};
end


methods (Test)
function test_join(tc, p)
tc.verifyEqual(stdlib.join(p{1}, p{2}), p{3})
end
end

end
