classdef TestJoin < matlab.unittest.TestCase

properties (TestParameter)
p = {{"", "", ""}, ...
{"a", "", "a"}, ...
{"", "a", "a"}, ...
{"a/b/", "c/", "a/b/c"}, ...
{"/", "", "/"}, ...
{"", "/", "/"}, ...
{"a", "b//", "a/b"}, ...
{"a//", "b//", "a/b"}, ...
{"a/b/../", "c/d/../", "a/b/../c/d/.."}, ...
{"a/b", "..", "a/b/.."}, ...
{"a/b", "c/d", "a/b/c/d"}, ...
{"ab/cd", "/ef", "/ef"}, ...
{stdlib.homedir(), "", stdlib.homedir()}, ...
{matlabroot, "bin", stdlib.posix(matlabroot + "/bin")}
}
end

methods (Test)
function test_join(tc, p)
tc.verifyEqual(stdlib.join(p{1}, p{2}), p{3})
end
end

end
