classdef (SharedTestFixtures={ matlab.unittest.fixtures.PathFixture(fileparts(fileparts(mfilename('fullpath'))))}, ...
          TestTags = {'R2019a', 'pure'}) ...
    TestStem < matlab.unittest.TestCase

properties (TestParameter)

p = {...
{"/a/b/c", "c"}, ...
{"/a/b/c/", ""}, ...
{"a/b/c/", ""}, ...
{"a/b/c.txt", "c"}, ...
{"a/b/c.txt.gz", "c.txt"}, ...
{"a/b/.c", ".c"}, ...
{'a/b/.c', '.c'}, ...
{".config", ".config"}, ...
{"", ""}, ...
{'', ''}
}
end


methods (Test)

function test_stem(tc, p)
tc.verifyEqual(stdlib.stem(p{1}), p{2})
end

end

end
