classdef TestJoin < matlab.unittest.TestCase

properties (TestParameter)
p = {{"", "", ""}, ...
{"a", "", "a"}, ...
{"", "a", "a"}, ...
{"a/b/", "c", fullfile("a", "b", "c")}, ...
{"/", "", "/"}, ...
{"", "/", "/"}, ...
{"a", "b", fullfile("a", "b")}, ...
{"a/b/../", "c/d/..", fullfile("a", "b", "..", "c", "d", "..")}, ...
{"a/b", "..", fullfile("a", "b", "..")}, ...
{"a/b", "c/d", fullfile("a", "b", "c", "d")}, ...
{"ab/cd", "/ef", "/ef"}, ...
{stdlib.homedir(), "", stdlib.homedir()}, ...
{matlabroot, "bin", fullfile(matlabroot, "bin")}
}
end

methods (Test, TestTags="pure")
function test_join(tc, p)
tc.verifyEqual(stdlib.join(p{1}, p{2}), p{3})
end
end

end
