%% FUNCTION_BACKENDS
% a compile-time database of which backends are supported for each function.
% struct() is faster than Dictionary in Matlab for this type of use.

function b = functionBackends(funcName)
arguments
  funcName {mustBeTextScalar}
end

dps = ["dotnet", "python", "shell"];
jds = ["java", "dotnet", "shell"];
jps = ["java", "python", "shell"];
jdps = ["java", "dotnet", "python", "shell"];
ndps = ["native", "dotnet", "python", "shell"];
pjsn = ["python", "java", "shell", "native"];
ps = ["python", "shell"];
njpds = ["native", "java", "python", "dotnet", "shell"];

bks = struct(...
'cpu_load', jps, ...
'create_symlink', ndps, ...
'device', jps, 'hard_link_count', jps, 'inode', jps, 'set_modtime', jps, ...
'disk_available', jdps, 'disk_capacity', jdps, ...
'file_checksum', jds, ...
'filesystem_type', jdps, ...
'get_max_open_files', ps, 'is_char_device', ps, 'is_dev_drive', ps, 'is_mount', ps, 'is_removable', ps, ...
'get_owner', jdps, ...
'get_process_priority', dps, 'get_uid', dps, 'uptime', dps, ...
'get_username', jdps, 'hostname', jdps, 'is_admin', jdps, ...
'is_symlink', njpds, 'read_symlink', njpds, ...
'os_version', jdps, ...
'ram_free', jps, 'ram_total', jdps, ...
'samepath', pjsn);

b = bks.(funcName);

end
