name: "matlab-check"

runs:

  using: "composite"

  steps:

  - name: Check task
    if: ${{ matrix.release >= 'R2024a' }}
    uses: matlab-actions/run-build@v2
    with:
      startup-options: ${{ matrix.startup-options }}
      tasks: check

  - name: Upload CodeIssues
    if: failure()
    uses: actions/upload-artifact@v4
    with:
      name: ${{ matrix.release }}-${{ runner.os }}-codeissues
      path: .buildtool/CodeIssues.sarif
