name: "matlab-buildtool"

runs:

  using: "composite"

  steps:

  - name: Check task
    if: ${{ matrix.release >= 'R2024b' || startsWith(matrix.release, 'latest') }}
    uses: matlab-actions/run-build@v2
    with:
      startup-options: ${{ matrix.startup-options }}
      tasks: check

  - name: Non-Mex Test
    if: ${{ matrix.release >= 'R2024b' || startsWith(matrix.release, 'latest') }}
    uses: matlab-actions/run-build@v2
    with:
      startup-options: ${{ matrix.startup-options }}
      tasks: test

  - name: Mex Test
    if: ${{ matrix.release >= 'R2023a' || startsWith(matrix.release, 'latest') }}
    uses: matlab-actions/run-build@v2
    with:
      startup-options: ${{ matrix.startup-options }}
      tasks: mex test


  - name: Run tests (manual)
    if: ${{ matrix.release < 'R2023a' && !startsWith(matrix.release, 'latest') }}
    uses: matlab-actions/run-tests@v2
    with:
      source-folder: ${{ github.workspace }}
      select-by-folder: test
      strict: false
