name: "matlab-buildtool"

runs:

  using: "composite"

  steps:

  - name: Check task
    if: ${{ matrix.release >= 'R2024b' || startsWith(matrix.release, 'latest') }}
    uses: matlab-actions/run-build@v2
    with:
      startup-options: ${{ matrix.startup-options }}
      tasks: check

  - name: Non-Mex Test
    if: ${{ matrix.release >= 'R2024b' || startsWith(matrix.release, 'latest') }}
    uses: matlab-actions/run-build@v2
    with:
      startup-options: ${{ matrix.startup-options }}
      tasks: test

  - name: Mex Test
    if: ${{ matrix.release >= 'R2023a' || startsWith(matrix.release, 'latest') }}
    uses: matlab-actions/run-build@v2
    with:
      startup-options: ${{ matrix.startup-options }} -logfile ${{ matrix.release }}-${{ runner.os }}-test.log
      tasks: mex test


# note: "source-folder" is necessary, but watch out as it adds all subfolders to path too
# https://github.com/matlab-actions/run-tests?tab=readme-ov-file#run-matlab-tests
  - name: Run tests (manual)
    if: ${{ matrix.release < 'R2023a' && !startsWith(matrix.release, 'latest') }}
    uses: matlab-actions/run-tests@v2
    with:
      source-folder: ${{ github.workspace }}
      select-by-folder: test
      strict: false
      startup-options: -logfile ${{ matrix.release }}-${{ runner.os }}-test.log


  - name: upload logfile
    if: ${{ hashFiles(matrix.release-runner.os-test.log) != '' }}
    uses: actions/upload-artifact@v4
    with:
      name: ${{ matrix.release }}-${{ runner.os }}-test-log
      path: ${{ matrix.release }}-${{ runner.os }}-test.log
      retention-days: 1
