name: "matlab-buildtool"

runs:

  using: "composite"

  steps:

  - name: Check task
    if: ${{ matrix.release >= 'R2024b' || matrix.release == 'latest' || matrix.release == 'latest-including-prerelease' }}
    uses: matlab-actions/run-build@v2
    with:
      startup-options: ${{ matrix.startup-options }}
      tasks: check

  - name: Test task
    if: ${{ matrix.release >= 'R2022b' || matrix.release == 'latest' || matrix.release == 'latest-including-prerelease' }}
    uses: matlab-actions/run-build@v2
    with:
      startup-options: ${{ matrix.startup-options }}
      tasks: test


  - name: Run tests (manual)
    if: ${{ matrix.release < 'R2022b' && matrix.release != 'latest' && matrix.release != 'latest-including-prerelease' }}
    uses: matlab-actions/run-tests@v2
    with:
      select-by-folder: test
