name: "matlab-mex"

runs:

  using: "composite"

  steps:

  - name: Mex Test
    if: ${{ matrix.release >= 'R2024b' }}
    uses: matlab-actions/run-build@v2
    with:
      startup-options: ${{ matrix.startup-options }} -logfile ${{ matrix.release }}-${{ runner.os }}-test.log
      tasks: test:mex test:exe
