function [head, body] = index_html(styleName, pkg_name, tagline, git_txt, project_url)

head = ["<!DOCTYPE html>", ...
'<head lang="en">',...
'<meta charset="UTF-8">', ...
'<meta name="color-scheme" content="dark light">', ...
'<meta name="viewport" content="width=device-width, initial-scale=1">', ...
sprintf('<meta name="generator" content="Matlab %s">', matlabRelease().Release), ...
sprintf('<link rel="stylesheet" href="%s">', styleName), ...
"<title>" + pkg_name + " API</title>", ...
"</head>"];

body = [
"<body>", ...
sprintf('<h1>%s API</h1>', pkg_name), ...
sprintf('<p>%s</p>', tagline), ...
sprintf('<p>%s</p>', git_txt)];

body = [body, ...
'<p id="userAgent"></p>', ...
'<script>document.getElementById("userAgent").textContent = navigator.userAgent;</script>', ...
"<p>Project URL: <a href=" + project_url + ">" + project_url + "</a></p>", ...
"<h2>API Reference</h2>"];
end
