name: ci-nojvm

on:
  push:
    paths:
    - "**.m"
    - ".github/workflows/ci-nojvm.yml"

jobs:

  NoJVM:
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
        release: [latest]
        startup-options: ["-nojvm"]

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/workflows/composite-install-matlab

    - uses: ./.github/workflows/composite-buildtool
