name: ci-nojvm

on:
  push:
    paths:
    - "**.m"
    - "**.h"
    - "**.cpp"
    - ".github/workflows/ci-nojvm.yml"
    - ".github/workflows/*/action.yml"
    - "!private/publish_gen_index_html.m"
    - "!scripts/**"

# avoid wasted runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  NoJVM:
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}

    name: ${{ matrix.release }}-${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
        release: [R2023b, R2025a]
        startup-options: ["-nojvm"]

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/workflows/composite-install-matlab

    - name: Matlab tell External Language Interface versions
      uses: matlab-actions/run-command@v2
      with:
        command: stdlib.platform_tell()

    - name: Fortran FC
      if: runner.os == 'macOS'
      run: echo "FC=gfortran-14" >> $GITHUB_ENV

    - name: No Java, no Mex tests
      uses: ./.github/workflows/composite-nomex
