name: ci-nojvm

on:
  push:
    paths:
    - "**.m"
    - "**.h"
    - "**.cpp"
    - ".github/workflows/ci-nojvm.yml"
    - "!private/publish_gen_index_html.m"
    - "!octave_build.m"
    - "!scripts/**"

# avoid wasted runs
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:

  NoJVM:
    timeout-minutes: 15
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, macos-latest, windows-latest]
        release: [latest]
        startup-options: ["-nojvm"]

    steps:
    - uses: actions/checkout@v4

    - uses: ./.github/workflows/composite-install-matlab

    - name: Fortran FC
      if: runner.os == 'macOS'
      run: echo "FC=gfortran-14" >> $GITHUB_ENV

    - name: No Java, no Mex tests
      uses: ./.github/workflows/composite-nomex

    - name: No Java, with MEX tests
      uses: ./.github/workflows/composite-mex
