name: ci-nojvm

on:
  push:
    paths:
    - "**.m"
    - ".github/workflows/ci-nojvm.yml"

jobs:

  NoJVM:
    timeout-minutes: 60
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest,macos-latest,windows-latest]
        release: [R2024b]

    steps:

    - name: Install MATLAB
      uses: matlab-actions/setup-matlab@v2
      with:
        release: ${{ matrix.release }}

    - uses: actions/checkout@v4

    - name: Run Matlab tests (buildtool)
      timeout-minutes: 10
      uses: matlab-actions/run-build@v2
      with:
        startup-options: -nojvm
